apiVersion: v1
kind: Service
metadata:
  labels:
    app: khalims-heart
  name: khalims-heart-node-port-service
spec:
  type: NodePort # 服务类型
  ports:
  - port: 80 # Service端口
    protocol: TCP # 协议
    targetPort: 80 # 容器端口
    nodePort: 30001  # 对外暴露的端口，可以指定
  selector:
    app: khalims-heart # 指定关联Pod的标签
